name: moneyjot
description: A modern fintech app built with Flutter.
publish_to: "none" # This means the package won't be published to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter Icons
  cupertino_icons: ^1.0.2

  # Firebase Core (initialization)
  firebase_core: ^2.30.0

  # Firebase Authentication
  firebase_auth: ^4.17.0

  # Firestore for storing user data
  cloud_firestore: ^4.15.0

  # Biometric authentication
  local_auth: ^2.1.4

  # State management (optional but helpful)
  provider: ^6.1.1

  # Displaying SVG assets (optional)
  flutter_svg: ^2.0.10+1

  # Image caching (optional for performance)
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - 'assets/images/background.jpg'
    - 'assets/images/login_bg.jpg'
   

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf